typography_spectrum: 0.7740769255906343
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5896757179871202
  lightness: 0.7943799651693553
  saturation: 0.6994508586358279
  rhythmicContrast: 0.25934090930968523
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8425254351459444
analytics:
  google: null
  facebook: null
  twitter: null
name: eyestormenterprises
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: VJ EYESTORM
purpose: []
